### ISSUE TITLE
Negative length in GeneModelGenerationService.determineGeneFeatures

### ISSUE THREAD

**Issue by jchriste-jcvi** [JCVenterInstitute/VIGOR4#22]
With master@96585d

java.lang.IllegalArgumentException: length can not be negative
    at org.jcvi.jillion.core.Range$Builder.assertValidCoordinates(Range.java:2856) ~[vigor-4.1.20200430-192814-96585d9-jar-with-dependencies.jar:?]
    at org.jcvi.vigor.service.GeneModelGenerationService.determineGeneFeatures(GeneModelGenerationService.java:394) ~[vigor-4.1.20200430-192814-96585d9-jar-with-dependencies.jar:?]
    at org.jcvi.vigor.service.GeneModelGenerationService.generateGeneModel(GeneModelGenerationService.java:57) ~[vigor-4.1.20200430-192814-96585d9-jar-with-dependencies.jar:?]
    at org.jcvi.vigor.Vigor.generateGeneModels(Vigor.java:398) ~[vigor-4.1.20200430-192814-96585d9-jar-with-dependencies.jar:?]
    at org.jcvi.vigor.Vigor.modelsFromNucleotideRecord(Vigor.java:300) ~[vigor-4.1.20200430-192814-96585d9-jar-with-dependencies.jar:?]
    at org.jcvi.vigor.Vigor.generateAnnotations(Vigor.java:243) ~[vigor-4.1.20200430-192814-96585d9-jar-with-dependencies.jar:?]
    at org.jcvi.vigor.Vigor.run(Vigor.java:90) [vigor-4.1.20200430-192814-96585d9-jar-with-dependencies.jar:?]
    at org.jcvi.vigor.Application.main(Application.java:12) [vigor-4.1.20200430-192814-96585d9-jar-with-dependencies.jar:?]

**Comment by dkatzel-ncats** [comment]
is this a range for a gene that is in the opposite direction? Jillion does have a DirectedRange if you mean the stop is before the start coordinate

**Comment by jchriste-jcvi** [comment]
Stalker!

**Comment by jchriste-jcvi** [comment]
I haven't looked into it, but when I encountered it before it was just an error. We tried to make the code work in the forward direction while keeping a note of which strand it was on. It was simpler for adding the reverse strand case which most of the code hadn't been accounting for. I'll let you know.
